'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cancion
    Public Property id_cancion As Integer
    Public Property nombre As String
    Public Property interprete As String
    Public Property album As String
    Public Property duracion As System.TimeSpan
    Public Property tamaño As String

End Class
