'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class musicaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=musicaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property artista() As DbSet(Of artista)
    Public Property cancion() As DbSet(Of cancion)
    Public Property genero() As DbSet(Of genero)
    Public Property persona() As DbSet(Of persona)
    Public Property recientes() As DbSet(Of recientes)

End Class
